@echo off
cd /d "%~dp0"
echo Uruchamianie: Zuzycie energii Polska...
py Zuzycie_energii_polska_py.py
echo Uruchamianie: Mieszkania Polska...
py mieszkania_polska_py.py
echo Uruchamianie: Zuzycie energii Wojewodztwa...
py Zuzycie_energii_wojewodztwa_py.py
echo Uruchamianie: Mieszkania Wojewodztwa...
py mieszkania_wojewodztwa_py.py
echo.
echo === ZADANIE 4 – PROGNOZY ZMIENNYCH OBJASNIAJACYCH ===
echo Uruchamianie: Prognoza zmiennych – Energia Polska...
py prognoza_zmiennych_energia_polska_py.py
echo Uruchamianie: Prognoza zmiennych – Energia Wojewodztwa...
py prognoza_zmiennych_energia_woj_py.py
echo.
echo === ZADANIE 5 – PROGNOZA WARUNKOWA ===
echo Uruchamianie: Prognoza warunkowa – Energia Polska...
py prognoza_warunkowa_energia_polska_py.py
echo Uruchamianie: Prognoza warunkowa – Energia Wojewodztwa...
py prognoza_warunkowa_energia_woj_py.py
echo Gotowe. Pliki PNG zapisane w folderze projektu.
pause
