@echo off
cd /d "%~dp0"
echo Uruchamianie: Zuzycie energii Polska...
py Zuzycie_energii_polska_py.py
echo Uruchamianie: Mieszkania Polska...
py mieszkania_polska_py.py
echo Uruchamianie: Zuzycie energii Wojewodztwa...
py Zuzycie_energii_wojewodztwa_py.py
echo Uruchamianie: Mieszkania Wojewodztwa...
py mieszkania_wojewodztwa_py.py
echo Gotowe. Pliki PNG zapisane w folderze projektu.
pause
